### ISSUE TITLE
Use in another project

### ISSUE THREAD

**Issue by tappi287** [TonyWhitley/rF2headlights#2]
Hey mate,

thank you for creating this! Do you have any license you share this under or just public domain do what you like?

I'd like to integrate your Headlights functionality in my [rf2-settings-widget](https://github.com/tappi287/rf2_video_settings).

Cheers,
Stefan

**Comment by TonyWhitley** [comment]
Hi Stefan,
First, thanks for asking.  There is no license, feel free to do what you like with it.  I'll have to look at your program, it looks similar in intent to something I tried to do but ran out of steam with [https://github.com/TonyWhitley/rFactory](https://github.com/TonyWhitley/rFactory).  I have to warn you that there is a bug in Headlights that I have fixed but I can't build it at the moment, I think it's something to do with the way git handles submodules. I tried to fix it and got frustrated and stopped before I threw my PC out of the window!

Feel free to ask questions, I'll answer them if I can!
Tony

**Comment by TonyWhitley** [comment]
Ah, I see you know about that - sorry, I've only just seen your MR!  Does that mean you know about my other related project [https://github.com/TonyWhitley/ScriptedJsonEditor](https://github.com/TonyWhitley/ScriptedJsonEditor) which _does_ work (I use it but couldn't face trying to explain to others how to use it)

**Comment by tappi287** [comment]
Ah, cool, thanks! Had a look at the headlights code yesterday and I think I need to adapt it to my app anyway since I have the luxury option of using an event loop with either eel or gevent. It's really cool to have a JS app as the gui as you don't have to worry about blocking the main thread. Everything is async out of the box. If one is brave enough to face the uglyness of JS code of course xD

Hehe, yeah, I had a look at rFactory last year. Just added some quick fixes because I was not able to run it on my system with a non-default rF2 install location. Btw, this is the module that I use to locate rFactor by steam app id and things like the chief by their reg keys in one module: [steam_utils](https://github.com/tappi287/rf2_video_settings/blob/master/rf2settings/valve/steam_utils.py).

Nope, didn't know about the Json Editor. Think it is a cool concept but a very different target audience. I, myself included, really just wanted a quick method to change between player.json presets. Which is exactly what the settings-widget does now. So one can fire up a High-ish settings preset for say a nice weather race with limited grid size. Eye candy settings for replays and performance-ish settings for the 200car LeMan race in the rain at night.. and so on :)

And by the way, thanks for you rf2servernotify code, I searched ages to find the syntax for the command line argument to join a password protected server. How should one know that you need to send -connect:= instead of -connect= xD

I'll let you know whenever I have implemented something or have question I ran into. Thank you!

**Comment by tappi287** [comment]
I have finished a first implemention and was able to remove the threading dependency. set_timer is now done with a simple gevent timer.
I've encountered two problems though: 1 is the sim_info.vehicleName() method is not available in your latest py-rf2sharedmemory version. Referring to this [line in rf2headlights](https://github.com/TonyWhitley/rF2headlights/blob/d96ff9ef0c58df07347bc6cd87202a16ab9a0ddb/rF2headlights.py#L274).
And I had to comment out the whole class of rF2TrackRules and rF2Rules in the rf2data module of the py-shared memory to get it to work. The rF2TrackRulesStage Enum is somehow not accepted as valid ctypes type.

Did some short test sessions and it seems to work well so far anyway :)

**Comment by TonyWhitley** [comment]
Good stuff :)  It sounds like you've done what I tried, to separate the set up GUI from the code that actually flashes the lights. The problems are what I hit, I think I updated pyRfactor2SharedMemory to add stuff and then managed to lose the changes somewhere (despite years of being the company expert on another source code system I struggle to get git to do what I want!)

Prompted by your question about licensing and also watching a video about it I've added an MIT license to my code.  It's just about the most open license there is and I hope makes the "can I use your code?" question clear to you or anyone else.

I'm currently suffering a complete lack of enthusiasm for writing software but when I get my mojo back I'll fix pyRfactor2SharedMemory.

Good luck with your project,
Tony

**Comment by TonyWhitley** [comment]
FYI: I downloaded your project and after hacking furiously to set up eel, vue and NPM I got it to build.  No idea what I might do with it now that I have managed that much!

**Comment by TonyWhitley** [comment]
FYI 2:
> I've encountered two problems though: 1 is the sim_info.vehicleName() method is not available in your latest py-rf2sharedmemory version. Referring to this [line in rf2headlights](https://github.com/TonyWhitley/rF2headlights/blob/d96ff9ef0c58df07347bc6cd87202a16ab9a0ddb/rF2headlights.py#L274).

That was definitely working.

**Comment by tappi287** [comment]
Haha, nice. Have to admit I've never thought of someone else needing to set it up. I use PyCharm Pro which will find the pipenv.lock aswell as the package.json and setup everything automagically.

To FYI2: The vehicleName method is not there for me in the (latest Version)[https://github.com/TonyWhitley/pyRfactor2SharedMemory/blob/c6aa2a150ccc0a1c78f71319c7262eeb2d672336/sharedMemoryAPI.py#L15] of the SimInfoAPI class. Anyway it works flawless so far. Just received a McLaren GT3 Rim with Rotary encoders. Seems like the event loop doesnt't like constantly pressed buttons. Have to check that.
