### ISSUE TITLE
rF2 headlights now have 3 modes

### ISSUE THREAD

**Issue by PauloMViegas** [TonyWhitley/rF2headlights#3]
Hi Tony,

Thanks for this great piece of software.
But rFactor now has a third mode on the headlights: Auto.
Now, instead of having an even cicle of 2 (on/off), we an odd cicle of 3 (on/off/auto).
With the sofware as is, Flashing lights doesn't end has it was before.
At least this issue appens with the Oreca LMP2 car that I use.

Can you please cmake a new version of the software?...

Thanks in advance.

Cheers

Paulo Viegas

**Comment by TonyWhitley** [comment]
I haven't played rFactor in a while and when I read the change notes I thought the headlight operation was the same if "automatic headlights" was turned off but now I check I see it is as you say.  I will look into fixing it and releasing a new version.

Thanks for pointing it out,
Tony

**Comment by TonyWhitley** [comment]
New version V1.9.74

**Comment by PauloMViegas** [comment]
I mate,

It is me that should thank you for such a great piece of software :)

Cheers.

TonyWhitley ***@***.***> escreveu no dia segunda, 24/05/2021
à(s) 12:34:

**Comment by PauloMViegas** [comment]
I Tony,

Can you help me with the installation with the new release files?...
I don't remember the file installation sequence...

Thanks in advance

Paulo

TonyWhitley ***@***.***> escreveu no dia segunda, 24/05/2021
à(s) 21:49:

**Comment by TonyWhitley** [comment]
https://github.com/TonyWhitley/rF2headlights/wiki

**Comment by PauloMViegas** [comment]
That's it... :D

Thanks once again mate.

A terça, 25/05/2021, 11:26, TonyWhitley ***@***.***> escreveu:

**Comment by PauloMViegas** [comment]
HI Tony.

I did everything as explained in
https://github.com/TonyWhitley/rF2headlights/wiki
But when I run  rF2headlights.exe, I can´t assign any controller... :(
Even when I use the previous headlightControls.ini file it doesn't work.
What can I be doing wrong?...

Thanks for your help.

PV

Paulo Viegas ***@***.***> escreveu no dia terça,
25/05/2021 à(s) 11:29:

**Comment by TonyWhitley** [comment]
I haven't changed anything to do with assigning controllers so I can't guess what the problem might be.  Does it still work with the previous version?  Try downloading the debug version https://github.com/TonyWhitley/rF2headlights/releases/download/V1.9.75/rF2headlightsDEBUG.exe and running that, there may be clues in the console window which runs behind the GUI

**Comment by PauloMViegas** [comment]
Thanks mate.

I'm going to do that. ;)

A quinta, 3/06/2021, 11:17, TonyWhitley ***@***.***> escreveu:

**Comment by PauloMViegas** [comment]
Hi Tony,

Still doesn't work and I don't have the previous version to test it again.
:(
Do I have to copy the .exe file to a specific rFactor folder?...
I have the rFactor installation folder in a different disk: System on C:
and all the games in J:
On the previous version there were no issues with that, so I assumed that
on this version it would me the same.
Please help me. This piece of software is so useful and I miss it a lot.

Cheers mate.

Paulo

TonyWhitley ***@***.***> escreveu no dia quinta, 3/06/2021
à(s) 11:17:

**Comment by PauloMViegas** [comment]
Hi Tony,

Sorry to bother you again.
Do you have the rF2headlights only On/Off version that was downloadable in
December?
Can you send it to me?
Thanks in advance.

Paulo

TonyWhitley ***@***.***> escreveu no dia quinta, 3/06/2021
à(s) 11:17:

**Comment by TonyWhitley** [comment]
All I have are the releases at
https://github.com/TonyWhitley/rF2headlights/releases

I tried the current release last night (first time I have played rFactor
for weeks) and it worked for me though possibly it was unstable (difficult
to be sure as rFactor was unstable as well, it took about 2 hours to run a
30min race)

**Comment by PauloMViegas** [comment]
Hi Tony,

I'm really pissed off with Studio 397... and with me.
Your previous release was just fine.
Only now I discovered that with the new UI, they implemented Auto
headlights On/Off on the Difficulty tab:

[image: Captura de ecrã 2021-06-22 120449.jpg]
[image: Captura de ecrã 2021-06-22 120540.jpg]
And putting by default On... instead of adding a Flashing key in the
'Assing' tab... what a morons...

The old UI didn't had this option...
[image: Captura de ecrã 2021-06-22 121207.jpg]
That's why I thought it was a new addition and not an option.

In conclusion, I induced you in an error and for that I apologise. Your
previous software was fine and stable.
I am so sorry for that. It was my fault you changed the software. :(
Thank you for everything.

Paulo

TonyWhitley ***@***.***> escreveu no dia terça, 22/06/2021
à(s) 11:06:

> All I have are the releases at
> https://github.com/TonyWhitley/rF2headlights/releases
>
> I tried the current release last night (first time I have played rFactor
> for weeks) and it worked for me though possibly it was unstable (difficult
> to be sure as rFactor was unstable as well, it took about 2 hours to run a
> 30min race)
>

**Comment by TonyWhitley** [comment]
No problem Paulo, I rely on people testing my software (on different
computers, different languages etc. etc) and the next person who says it
doesn't work I can say "Paulo found..." :)

Using the program the other night I remembered a bug - it turns the lights
off in the pits and if it's dark then you get disqualified for not having
the lights on.  So there will be a new version soon.
-- 
Tony

**Comment by PauloMViegas** [comment]
Thanks for being understandable Tony.
You can return to the old and stable version and make the remark that only
works with Autheadlights option 'Off' :)

Cheers mate

Paulo

TonyWhitley ***@***.***> escreveu no dia terça, 22/06/2021
à(s) 16:20:

> No problem Paulo, I rely on people testing my software (on different
> computers, different languages etc. etc) and the next person who says it
> doesn't work I can say "Paulo found..." :)
>
> Using the program the other night I remembered a bug - it turns the lights
> off in the pits and if it's dark then you get disqualified for not having
> the lights on. So there will be a new version soon.
> --
> Tony
>
>
